
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 29 16:25:38 CST 2020
//----------------------------------------------------

package Backend.FlexYCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEABRE = 29;
  public static final int DOSPUNTOS = 32;
  public static final int TAMAÑOid = 11;
  public static final int ALAZARid = 9;
  public static final int ABRECORCHETE = 30;
  public static final int ENTERO = 40;
  public static final int NUMMUERTES = 36;
  public static final int FACIL = 14;
  public static final int PLANETAS = 4;
  public static final int PLANETASNEUTRALES = 3;
  public static final int NEUTRALES = 21;
  public static final int DIFICIL = 15;
  public static final int MAPA = 2;
  public static final int NOMBREid = 6;
  public static final int IDMAPA = 39;
  public static final int FINALIZACIONid = 27;
  public static final int TIPOJUGADORid = 25;
  public static final int ID = 5;
  public static final int EOF = 0;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int COMILLA = 33;
  public static final int COMA = 34;
  public static final int CIERRACORCHETE = 31;
  public static final int NAVESid = 7;
  public static final int PLANETASid = 24;
  public static final int HUMANO = 16;
  public static final int MOSTRARNAVESid = 22;
  public static final int MOSTRARESTADISTICASid = 23;
  public static final int CORCHETECIERRA = 28;
  public static final int IDid = 10;
  public static final int PRODUCCIONid = 26;
  public static final int FILASid = 12;
  public static final int JUGADORES = 41;
  public static final int ACUMULARid = 20;
  public static final int COLUMNASid = 17;
  public static final int FALSE = 38;
  public static final int MAPACIEGOid = 19;
  public static final int PLANETASNEUTRALESid = 18;
  public static final int Comilla = 13;
  public static final int IDPLANETA = 35;
  public static final int PORMUERTESid = 8;
}

