/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Clases.Jugador;
import Backend.Clases.Mapa;
import Backend.Clases.Planeta;
import Backend.Clases.PlanetaNeutral;
import Backend.Clases.Tablero;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author astridmc
 */
public class Principal extends javax.swing.JFrame {

    public static boolean creado;
    boolean inicioJuego;
    ArrayList<Planeta> planetas;
    ArrayList<Jugador> jugadores = new ArrayList();
    ArrayList<PlanetaNeutral> planetasNeutrales = new ArrayList();
    Tablero tablero;
    Mapa mapa = new Mapa();
    Propiedades propiedades;
    JFileChooser seleccionar = new JFileChooser();
    String prop = null;
    PanelJuego panelJuego;

    /**
     * Creates new form Principal
     */
    public Principal() {

        initComponents();
        diseño();
        //menuBarra.setBackground(new java.awt.Color(56, 1, 57));
        //this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPanel = new javax.swing.JPanel();
        menuBarra = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoJuego = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cargarArchivo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konquest");

        imagenPanel.setBackground(new java.awt.Color(0, 35, 75));
        imagenPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        menuBarra.setBackground(new java.awt.Color(56, 1, 57));
        menuBarra.setForeground(new java.awt.Color(255, 0, 0));
        menuBarra.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N
        menuBarra.setPreferredSize(new java.awt.Dimension(118, 40));

        jMenu1.setForeground(new java.awt.Color(254, 254, 254));
        jMenu1.setText("Juego");
        jMenu1.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N

        nuevoJuego.setBackground(new java.awt.Color(56, 1, 57));
        nuevoJuego.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        nuevoJuego.setForeground(new java.awt.Color(254, 254, 254));
        nuevoJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/5e72b43074a4d_1584575626_5e72b430749ed.png"))); // NOI18N
        nuevoJuego.setText("Nuevo");
        nuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJuegoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoJuego);

        menuCerrar.setBackground(new java.awt.Color(56, 1, 57));
        menuCerrar.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        menuCerrar.setForeground(new java.awt.Color(254, 254, 254));
        menuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/salir.png"))); // NOI18N
        menuCerrar.setText("Salir");
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(menuCerrar);

        menuBarra.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(254, 254, 254));
        jMenu2.setText("Cargar");
        jMenu2.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N

        cargarArchivo.setBackground(new java.awt.Color(56, 1, 57));
        cargarArchivo.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        cargarArchivo.setForeground(new java.awt.Color(254, 254, 254));
        cargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/abrir.png"))); // NOI18N
        cargarArchivo.setText("Arhivo");
        cargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cargarArchivoMousePressed(evt);
            }
        });
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        jMenu2.add(cargarArchivo);

        menuBarra.add(jMenu2);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JLabel imagen = new JLabel();
    String fondo = "fondoSol.jpg";
    ImageIcon portada = new ImageIcon(fondo);
    private void imagenPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenPanelComponentResized
        System.out.println(inicioJuego);
        if (inicioJuego = true && panelJuego != null) {
            panelJuego.setVisible(false);
            System.out.println("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
            imagenPanel.add(panelJuego);
            panelJuego.setVisible(true);
            panelJuego.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
        }
        if (imagenPanel.getComponents().length > 0) {
            imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
            imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
            imagenPanel.remove(0);
            imagenPanel.add(imagen);
            System.out.println(imagenPanel.getComponent(0).getName());
        }
    }//GEN-LAST:event_imagenPanelComponentResized

    private void nuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJuegoActionPerformed
        propiedades = new Propiedades(this);
        propiedades.setVisible(true);
        try {
            mapa = propiedades.getMapa();
            planetas = propiedades.getPlanetas();
            planetasNeutrales = propiedades.getPlanetasNeutrales1();
            jugadores = propiedades.getJugadores();
            System.out.println(planetas.size());
            System.out.println(planetasNeutrales.size());
            inicioJuego();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error iniciando el Juego");
        }
    }//GEN-LAST:event_nuevoJuegoActionPerformed

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("jpg", "gif", "json");
        fileChooser.setFileFilter(imgFilter);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            File fileName = fileChooser.getSelectedFile();
            if ((fileName == null) || (fileName.getName().equals(""))) {
            } else {
                propiedades = new Propiedades(fileName.getName(), this);
                propiedades.setVisible(true);
                try {
                    if (propiedades.isCreado()) {
                        mapa = propiedades.getMapa();
                        planetas = propiedades.getPlanetas();
                        planetasNeutrales = propiedades.getPlanetasNeutrales1();
                        jugadores = propiedades.getJugadores();
                        System.out.println(planetas.size());
                        System.out.println(planetasNeutrales.size());
                        inicioJuego();
                    }

                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, "Error iniciando el Juego");
                }
                // txt.setText(fileName.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void cargarArchivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarArchivoMousePressed

    }//GEN-LAST:event_cargarArchivoMousePressed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuCerrarActionPerformed

    Planeta plan;

    void diseño() {
        setTitle("KONQUEST");
        setLocation(200, 100);
        setIconImage(new ImageIcon("nave.png").getImage());
        imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
        imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
        imagenPanel.add(imagen);
    }

    public void inicioJuego() {
        inicioJuego = true;
        panelJuego = new PanelJuego(planetas, jugadores, planetasNeutrales, mapa);
        System.out.println("iniciando ");
        imagenPanel.add(panelJuego);
        System.out.println(inicioJuego);
        if (inicioJuego = true && panelJuego != null) {
            panelJuego.setVisible(false);
            imagenPanel.add(panelJuego);
            panelJuego.setVisible(true);
            panelJuego.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
        }
        if (imagenPanel.getComponents().length > 0) {
            imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
            imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
            imagenPanel.remove(0);
            imagenPanel.add(imagen);
            System.out.println(imagenPanel.getComponent(0).getName());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cargarArchivo;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JMenuItem nuevoJuego;
    // End of variables declaration//GEN-END:variables
}
