/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import javax.swing.JFileChooser;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author astridmc
 */
public class Principal extends javax.swing.JFrame {

    JFileChooser seleccionar = new JFileChooser();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        diseño();
        panelJuego.setVisible(false);
        consola.setVisible(false);
        //menuBarra.setBackground(new java.awt.Color(56, 1, 57));
        //this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPanel = new javax.swing.JPanel();
        panelJuego = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        panelOPcionesJuego = new javax.swing.JPanel();
        btnJuegoNuevo = new javax.swing.JButton();
        PanelBotones = new javax.swing.JPanel();
        btnMedirDistancia = new javax.swing.JButton();
        btnVistaGeneral = new javax.swing.JButton();
        btnFinPartida = new javax.swing.JButton();
        btnFinTurno = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        menuBarra = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoJuego = new javax.swing.JMenuItem();
        menuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cargarArchivo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konquest");

        imagenPanel.setBackground(new java.awt.Color(0, 35, 75));
        imagenPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenPanelComponentResized(evt);
            }
        });

        panelJuego.setOpaque(false);

        consola.setBackground(new java.awt.Color(1, 1, 1));
        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane1.setViewportView(consola);

        btnJuegoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/5e72b43074a4d_1584575626_5e72b430749ed.png"))); // NOI18N
        btnJuegoNuevo.setText("Juego Nuevo");
        btnJuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoNuevoActionPerformed(evt);
            }
        });

        btnMedirDistancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/distancia.png"))); // NOI18N
        btnMedirDistancia.setText("Medir Distancia");
        btnMedirDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedirDistanciaActionPerformed(evt);
            }
        });

        btnVistaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/naves.png"))); // NOI18N
        btnVistaGeneral.setText("Vista General de La Flota");

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addComponent(btnMedirDistancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVistaGeneral)
                .addGap(0, 275, Short.MAX_VALUE))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVistaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMedirDistancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnFinPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/stop.png"))); // NOI18N
        btnFinPartida.setText("Finalizar Partida");

        btnFinTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/cambio.png"))); // NOI18N
        btnFinTurno.setText("Finalizar Turno");

        javax.swing.GroupLayout panelOPcionesJuegoLayout = new javax.swing.GroupLayout(panelOPcionesJuego);
        panelOPcionesJuego.setLayout(panelOPcionesJuegoLayout);
        panelOPcionesJuegoLayout.setHorizontalGroup(
            panelOPcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOPcionesJuegoLayout.createSequentialGroup()
                .addComponent(btnJuegoNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinPartida)
                .addGap(4, 4, 4)
                .addComponent(btnFinTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelOPcionesJuegoLayout.setVerticalGroup(
            panelOPcionesJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOPcionesJuegoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnJuegoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnFinPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFinTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(panelOPcionesJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelJuegoLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJuegoLayout.createSequentialGroup()
                .addComponent(panelOPcionesJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenPanelLayout.createSequentialGroup()
                .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBarra.setBackground(new java.awt.Color(56, 1, 57));
        menuBarra.setForeground(new java.awt.Color(255, 0, 0));
        menuBarra.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N
        menuBarra.setPreferredSize(new java.awt.Dimension(118, 40));

        jMenu1.setForeground(new java.awt.Color(254, 254, 254));
        jMenu1.setText("Juego");
        jMenu1.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N

        nuevoJuego.setBackground(new java.awt.Color(56, 1, 57));
        nuevoJuego.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        nuevoJuego.setForeground(new java.awt.Color(254, 254, 254));
        nuevoJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/5e72b43074a4d_1584575626_5e72b430749ed.png"))); // NOI18N
        nuevoJuego.setText("Nuevo");
        nuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJuegoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoJuego);

        menuCerrar.setBackground(new java.awt.Color(56, 1, 57));
        menuCerrar.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        menuCerrar.setForeground(new java.awt.Color(254, 254, 254));
        menuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/salir.png"))); // NOI18N
        menuCerrar.setText("Salir");
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(menuCerrar);

        menuBarra.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(254, 254, 254));
        jMenu2.setText("Cargar");
        jMenu2.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N

        cargarArchivo.setBackground(new java.awt.Color(56, 1, 57));
        cargarArchivo.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        cargarArchivo.setForeground(new java.awt.Color(254, 254, 254));
        cargarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/abrir.png"))); // NOI18N
        cargarArchivo.setText("Arhivo");
        cargarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cargarArchivoMousePressed(evt);
            }
        });
        cargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarArchivoActionPerformed(evt);
            }
        });
        jMenu2.add(cargarArchivo);

        menuBarra.add(jMenu2);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JLabel imagen = new JLabel();
    String fondo = "fondoSol.jpg";
    ImageIcon portada = new ImageIcon(fondo);
    private void imagenPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenPanelComponentResized

        imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
        imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
        imagenPanel.removeAll();
        imagenPanel.add(imagen);
    }//GEN-LAST:event_imagenPanelComponentResized

    private void nuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoJuegoActionPerformed

    private void cargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        // FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif"); 
        //fileChooser.setFileFilter(imgFilter);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            System.out.println("nada");
            File fileName = fileChooser.getSelectedFile();

            if ((fileName == null) || (fileName.getName().equals(""))) {
                
                //  txt.setText("...");
            } else {
                // txt.setText(fileName.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_cargarArchivoActionPerformed

    private void cargarArchivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarArchivoMousePressed

    }//GEN-LAST:event_cargarArchivoMousePressed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuCerrarActionPerformed

    private void btnJuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoNuevoActionPerformed
        Propiedades propiedades = new Propiedades();
        propiedades.setVisible(true);
    }//GEN-LAST:event_btnJuegoNuevoActionPerformed

    private void btnMedirDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedirDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMedirDistanciaActionPerformed

    void diseño() {
        setTitle("KONQUEST");
        setLocation(200, 100);
        setIconImage(new ImageIcon("nave.png").getImage());
        imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
        imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
        imagenPanel.add(imagen);
    }
    
    void obtenerYEscribirConsola(String texto){
        consola.setText(consola.getText()+"\n"+texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JButton btnFinPartida;
    private javax.swing.JButton btnFinTurno;
    private javax.swing.JButton btnJuegoNuevo;
    private javax.swing.JButton btnMedirDistancia;
    private javax.swing.JButton btnVistaGeneral;
    private javax.swing.JMenuItem cargarArchivo;
    private javax.swing.JTextArea consola;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JMenuItem nuevoJuego;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelOPcionesJuego;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables
}
