/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.Clases.Accion;
import Backend.Clases.Jugador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author astridmc
 */
public class VerFlotas extends javax.swing.JDialog {
    ArrayList<Accion> jugadorAcciones = new ArrayList();
    Accion guardaJuego = new Accion();
    /**
     * Creates new form VerFlotas
     * @param parent
     * @param modal
     * @param creador
     * @param jugadorAcciones
     */
    public VerFlotas(java.awt.Frame parent, boolean modal, Jugador jugador, ArrayList<Accion> jugadorAcciones) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        nombreJugador.setText(jugador.getNombre());
        this.jugadorAcciones = jugadorAcciones;
        llenarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInfoFlotas = new javax.swing.JTable();
        Aceptar = new javax.swing.JButton();
        nombreJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 235, 244));

        tablaInfoFlotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. de Flota", "Origen", "Destino", "Naves", "Porcentaje De Muertes", "Turno De Llegada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInfoFlotas.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        tablaInfoFlotas.setRowHeight(25);
        jScrollPane1.setViewportView(tablaInfoFlotas);

        Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontend/Imagenes/checkmark.png"))); // NOI18N
        Aceptar.setText("Aceptar");

        nombreJugador.setFont(new java.awt.Font("URW Bookman L", 3, 36)); // NOI18N
        nombreJugador.setText("jugador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(nombreJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void llenarTablas(){
        DefaultTableModel   modelo = new DefaultTableModel();
        modelo.addColumn("Legado");
        modelo.addColumn("No.Flota");
        modelo.addColumn("Origen");
        modelo.addColumn("Destino");
        modelo.addColumn("Naves");
        modelo.addColumn("% de Muetes");
        modelo.addColumn("TurnoLegada");
        tablaInfoFlotas.setModel(modelo);
        tablaInfoFlotas.setRowHeight(25);
        if(!jugadorAcciones.isEmpty()){
            for (int i = 0; i < jugadorAcciones.size(); i++) {
            modelo.addRow(guardaJuego.combertirArreglo(jugadorAcciones.get(i)));
        }
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreJugador;
    private javax.swing.JTable tablaInfoFlotas;
    // End of variables declaration//GEN-END:variables
}
